### ISSUE TITLE
Integrate Create.js with all main components

### ISSUE THREAD

**Issue by bergie** [flack/openpsa#16]
Since [Create.js](http://createjs.org/) can already run with MidCOM via [flack/createphp](/flack/createphp) we should provide it as the modern inline editing enabled by default.

**Comment by flack** [comment]
Looks like this wasn't meant to be. create.js never really worked with jquery ui 1.12, and it seems like that won't change. Feel free to reopen though if it does! :-)

fwiw, with the Symfonfy-based datamanager we can build something comparable (although I found in practice that ad-hoc implementations with a few fixed fields are usually sufficient)
