### ISSUE TITLE
DM2 Schema: Readonly fields are not stored

### ISSUE THREAD

**Issue by floegel** [flack/openpsa#17]
In the store function of midcom_helper_datamanager2_storage is stated (for readonly fields):
"Skip storage as we may raise exceptions if the field doesn't exist" 

That might not be the correct behaviour, because if we do not want a field to be stored we could use "storage => null" in the schema. Besides that, it might be expected that the field is actually stored.

**Comment by flack** [comment]
This works differently in new dm (readonly only sets the appropriate attribute on the rendered HTML), old DM2 will remain unchanged for backward compat (but nothing is using it anymore :-)) => Closing as fixed

**Comment by sfaujour** [comment]
At least, this just took 5 yrs to fix.
