### ISSUE TITLE
set_account & prepare_password for legacy not working

### ISSUE THREAD

**Issue by gudd** [flack/openpsa#182]
The check for already used passwords does not work with legacy passwords, because it only
passes password to midcom_connection::prepare_password - causing a random salt and therefore an always different encrypted password and so the check always results in true.

See org_openpsa_user_accounthelper::set_account

Also currently passwords can only be 8 characters long due to used crypt function with 2 characters Salt.
See midcom_connection::prepare_password.

**Comment by flack** [comment]
8 chars limitation was removed by switching to password_hash a while ago. The already used pw check was refactored around that time, too. So the issue should be fixed now
