### ISSUE TITLE
Notices from midcom_application while using command

### ISSUE THREAD

**Issue by gudd** [flack/openpsa#185]
While using Command via console - the SERVER_PORT may not be set in _SERVER array:

"Notice: Undefined index: SERVER_PORT in /home/gudd/workspace/lh_london/vendor/openpsa/midcom/lib/midcom/application.php on line 390"

**Comment by flack** [comment]
Does this still happen on dev-master (both miscom-console & openpsa)? I recently fixed a similar issue, it might affect this problem, too

**Comment by gudd** [comment]
Yes you are right - if i use midcom-console, which adds the values it works.
I used the symfony one.
Thanks!
